### ISSUE TITLE
removeKnob does not work

### ISSUE THREAD

**Issue by tuoxiansp** [Raathigesh/retoggle#10] opened 2018-12-01 08:58 UTC
Changed app.tsx like this:
```
export default function App() {
    const [ useIcon ] = useBooleanKnob('Use Icon', true)

    return useIcon ? <Icon /> : <div>123abc</div>
}
```

then switch 'Use Icon' to false.

Component Icon was unmounted, but knobs were still there .

**Comment by Raathigesh** [comment] 2018-12-02 10:14
The behavior seems to be correct. Why would you except the knob not to be there?

**Comment by Raathigesh** [comment] 2018-12-03 08:43
As far as the `useBooleanKnob()` statement is there in the component, the knob would be visible. In the title of the issue, you wrote `removeKnob does not work`. But in your example, I haven't seen any `removeKnob` method.

**Comment by tuoxiansp** [comment] 2018-12-03 09:12
My bad.. I haven't showed all the code.

![image](https://user-images.githubusercontent.com/3960056/49363424-98d45f80-f71c-11e8-8db2-5377cfaafa78.png)

This is the diff .

And code:
```
export default function App() {
    const [ useIcon ] = useBooleanKnob('Use Icon', true)

    return (
        <Fragment>
            <Inspector />
            {useIcon ? <Icon /> : <div>123abc</div>}
        </Fragment>
    )
}
```

Gif:
https://static.ucloud.cn/50e078ad8b894614b38712b247d1d135.gif

This is the code of `useColorKnob`.
![image](https://user-images.githubusercontent.com/3960056/49363888-d2599a80-f71d-11e8-8849-ecdcef416400.png)

When <Icon> was unmounted, `removeKnob` was called. But 'knobs' were still there.

**Comment by Raathigesh** [comment] 2019-03-08 23:56
I'm closing this for now. Feel free to re-open if you feel like the issue is not yet resolved. Happy to look into it again.

**Closed by Raathigesh** 2019-03-08 23:56 UTC
Labels: question
